### ISSUE TITLE
725ecb9 - unlimited minning

### ISSUE THREAD

**Issue by Detoeni** [DayZMod/DayZ#416]
No repro
I went to small rock on coast and started mining stone. before any text had been shown on screen I looked away. when text showed it had a minus number remaining, and mining never ended until I moved away from rock.
Tried to repro but rock would only ever give a single rock after this point.
![2015-04-25_00003](https://cloud.githubusercontent.com/assets/8584071/7332873/3b9d83e6-eb4f-11e4-8517-d9bb2d70705d.jpg)

**Comment by R4Z0R49** [comment]
It looks like the private tags was broken on that script its been fixed now. Also fixed the issue for mining with a sledgehammer.

Right clicking on a sledge hammer creates a blank text popup

**Comment by thcNox** [comment]
On Dayz europa (1.8.5) This is still a problem. Occured a couple of hours ago to both me and Vidko.

**Comment by R4Z0R49** [comment]
Yea ill take another look see whats going on im not too worried about it. The working values for nutrition are still called as well as the break factor.

**Comment by thcNox** [comment]
The way to reproduce this we found is to first mine one rock, then look at that rock and select mine rock again to mine rock infinitely.
